export interface ChatMessage {
  id: string; role: 'user' | 'assistant' | 'system'; content: string;
  timestamp: string; model?: string; tokens?: number; latency?: number;
  sources?: { title: string; url: string; relevance: number }[];
}

export interface Workflow {
  id: string; name: string; description: string; status: 'active' | 'draft' | 'paused' | 'error';
  steps: number; lastRun: string; successRate: number; avgLatency: number;
  category: string; tags: string[]; createdBy: string; createdAt: string;
}

export interface Agent {
  id: string; name: string; description: string; model: string;
  status: 'online' | 'offline' | 'training' | 'error'; capabilities: string[];
  temperature: number; lastActive: string; totalRequests: number; avgResponseTime: number;
  systemPrompt: string; memory: { type: string; items: number }[];
}

export interface KnowledgeItem {
  id: string; title: string; content: string; type: 'document' | 'code' | 'article' | 'dataset';
  source: string; status: 'indexed' | 'processing' | 'failed'; chunks: number;
  embeddings: string; lastUpdated: string; tags: string[]; size: string;
}

export interface Prompt {
  id: string; name: string; content: string; model: string; temperature: number;
  maxTokens: number; variables: string[]; tags: string[]; version: number;
  author: string; createdAt: string; updatedAt: string;
}

export const mockChatMessages: ChatMessage[] = [
  { id: 'm1', role: 'user', content: 'What is the architecture of GPT-4?', timestamp: '2026-05-21T10:30:00Z', model: 'gpt-4' },
  { id: 'm2', role: 'assistant', content: 'GPT-4 is a multimodal large language model developed by OpenAI. It uses a transformer-based architecture with a mixture of experts (MoE) approach, consisting of 8 expert networks with ~220 billion parameters total (~55 billion shared). It supports text and image inputs and generates text outputs. The architecture includes improved reasoning capabilities, longer context windows up to 128K tokens, and enhanced safety alignment through RLHF.', timestamp: '2026-05-21T10:30:05Z', model: 'gpt-4', tokens: 342, latency: 1200, sources: [{ title: 'GPT-4 Technical Report', url: 'https://arxiv.org/abs/2303.08774', relevance: 0.98 }] },
  { id: 'm3', role: 'user', content: 'Can you explain RAG in simple terms?', timestamp: '2026-05-21T10:32:00Z', model: 'gpt-4' },
  { id: 'm4', role: 'assistant', content: 'Retrieval-Augmented Generation (RAG) is like giving an AI a library card. Instead of relying solely on its training data, the AI first searches a knowledge base for relevant documents, then uses those documents to generate a more accurate, up-to-date answer. Think of it as: search first, then generate. This reduces hallucinations and keeps responses grounded in real data.', timestamp: '2026-05-21T10:32:03Z', model: 'gpt-4', tokens: 189, latency: 890, sources: [{ title: 'RAG Paper: Retrieval-Augmented Generation', url: 'https://arxiv.org/abs/2005.11401', relevance: 0.95 }] },
  { id: 'm5', role: 'user', content: 'Write a Python function to merge two sorted arrays', timestamp: '2026-05-21T10:35:00Z', model: 'claude-4' },
  { id: 'm6', role: 'assistant', content: '```python\ndef merge_sorted_arrays(arr1: list[int], arr2: list[int]) -> list[int]:\n    """Merge two sorted arrays into one sorted array."""\n    result = []\n    i = j = 0\n    while i < len(arr1) and j < len(arr2):\n        if arr1[i] < arr2[j]:\n            result.append(arr1[i])\n            i += 1\n        else:\n            result.append(arr2[j])\n            j += 1\n    result.extend(arr1[i:])\n    result.extend(arr2[j:])\n    return result\n```\nThis runs in O(n+m) time and O(1) extra space (excluding output).', timestamp: '2026-05-21T10:35:05Z', model: 'claude-4', tokens: 256, latency: 1500 },
  { id: 'm7', role: 'user', content: 'Compare fine-tuning vs prompt engineering', timestamp: '2026-05-21T10:40:00Z', model: 'gpt-4' },
  { id: 'm8', role: 'assistant', content: '**Fine-tuning** updates model weights on domain-specific data for permanent behavior changes. Best for: specialized tasks, formatting requirements, new knowledge injection. Requires GPUs, data prep, and takes hours.\n\n**Prompt engineering** crafts input prompts to guide outputs without weight changes. Best for: quick prototyping, variable tasks, when you lack training data. No compute needed.\n\n**Key tradeoffs:** Fine-tuning offers deeper integration but higher cost; prompt engineering is flexible but less reliable for complex behaviors. Many prod systems use both - prompt engineering for routing, fine-tuned models for specific tasks.', timestamp: '2026-05-21T10:40:03Z', model: 'gpt-4', tokens: 410, latency: 1100 },
  { id: 'm9', role: 'user', content: 'Design a vector search system architecture', timestamp: '2026-05-21T10:45:00Z', model: 'claude-4' },
  { id: 'm10', role: 'assistant', content: 'A production vector search system requires:\n\n1. **Embedding Pipeline**: Document processors → chunking strategy → embedding model (text-embedding-3-large, etc.) → vector DB\n2. **Storage Layer**: Options include Pinecone, Weaviate, Qdrant, or pgvector. Key considerations: dimensionality (1536 for ada-002), index type (HNSW, IVF), and scalability\n3. **Query Flow**: User query → same embedding model → ANN search → hybrid ranking (vector similarity + keyword BM25) → reranking (cross-encoder) → results\n4. **Hybrid Search**: Combine dense vectors with sparse retrieval for better relevance\n5. **Filtering**: Metadata pre-filtering for tenant isolation, date ranges, content types\n6. **Monitoring**: Recall@K, latency P99, index freshness', timestamp: '2026-05-21T10:45:04Z', model: 'claude-4', tokens: 520, latency: 1800, sources: [{ title: 'Vector Search Architecture Guide', url: 'https://www.pinecone.io/learn/vector-search/', relevance: 0.92 }] },
  { id: 'm11', role: 'user', content: 'What are the latest advances in LLM safety?', timestamp: '2026-05-21T10:50:00Z', model: 'gpt-4' },
  { id: 'm12', role: 'assistant', content: 'Recent LLM safety advances include:\n\n1. **Constitutional AI**: Models self-improve using rule-based critiques rather than human feedback alone\n2. **Red-teaming automation**: LLMs generate adversarial prompts to find vulnerabilities at scale\n3. **Watermarking**: Statistical patterns in token selection make AI-generated text detectable\n4. **Guardrails**: Bouncer models that filter inputs/outputs in real-time (e.g., NVIDIA NeMo Guardrails)\n5. **RLHF refinements**: Better reward modeling reduces reward hacking and alignment tax\n6. **Unlearning**: Techniques to remove copyrighted or dangerous knowledge post-training\n7. **Interpretability**: Sparse autoencoders reveal features inside transformer activations (Anthropic\'s work)', timestamp: '2026-05-21T10:50:03Z', model: 'gpt-4', tokens: 480, latency: 1300, sources: [{ title: 'Constitutional AI', url: 'https://arxiv.org/abs/2212.08073', relevance: 0.94 }, { title: 'LLM Watermarking', url: 'https://arxiv.org/abs/2301.10226', relevance: 0.88 }] },
  { id: 'm13', role: 'user', content: 'Show me an example of a multi-agent system', timestamp: '2026-05-21T10:55:00Z', model: 'claude-4' },
  { id: 'm14', role: 'assistant', content: 'A multi-agent system for software development:\n\n```python\nclass AgentOrchestrator:\n    def __init__(self):\n        self.agents = {\n            "planner": PlannerAgent("gpt-4"),\n            "coder": CodingAgent("claude-4"),\n            "reviewer": ReviewAgent("gpt-4"),\n            "tester": TestAgent("claude-4"),\n        }\n    \n    async def run(self, task: str):\n        plan = await self.agents["planner"].plan(task)\n        code = await self.agents["coder"].write(plan)\n        review = await self.agents["reviewer"].review(code)\n        if review.approved:\n            tests = await self.agents["tester"].test(code)\n            return {"code": code, "tests": tests}\n        return self.run(review.feedback)\n```\nAgents communicate via structured messages. Each has specialized tools, memory, and guardrails. Orchestrator handles routing, conflict resolution, and state management.', timestamp: '2026-05-21T10:55:04Z', model: 'claude-4', tokens: 390, latency: 1600 },
  { id: 'm15', role: 'user', content: 'Explain the transformer attention mechanism', timestamp: '2026-05-21T11:00:00Z', model: 'gpt-4' },
  { id: 'm16', role: 'assistant', content: 'The attention mechanism computes weighted sums of values based on query-key compatibilities:\n\n**Attention(Q,K,V) = softmax(QK^T/√d)V**\n\nWhere:\n- **Q (Query)**: What the current token is looking for\n- **K (Key)**: What each token offers\n- **V (Value)**: The actual content of each token\n- **√d**: Scaling factor to prevent softmax saturation\n\n**Multi-head attention** runs this 8-96 times in parallel with different learned projections, then concatenates results. This lets models attend to different types of relationships (syntax, semantics, position) simultaneously.\n\nThe scaled dot-product is O(n²) in sequence length, which is why long-context is expensive - hence innovations like FlashAttention, sliding window attention, and Mamba.', timestamp: '2026-05-21T11:00:03Z', model: 'gpt-4', tokens: 450, latency: 1050, sources: [{ title: 'Attention Is All You Need', url: 'https://arxiv.org/abs/1706.03762', relevance: 0.99 }] },
  { id: 'm17', role: 'user', content: 'How do I deploy LLMs in production?', timestamp: '2026-05-21T11:05:00Z', model: 'claude-4' },
  { id: 'm18', role: 'assistant', content: 'Production LLM deployment stack:\n\n1. **Inference serving**: vLLM, TGI, or Triton Inference Server for self-hosted; API gateways for managed\n2. **Scaling**: Horizontal pod autoscaling based on queue depth, request batching for throughput\n3. **Caching**: Semantic cache (GPTCache) for redundant queries - saves 40-60% on costs\n4. **Monitoring**: Guardrails (content safety, PII), latency budgets (P99 < 3s), token tracking\n5. **Fallback**: Cascade from cheap→expensive models, graceful degradation\n6. **CI/CD**: A/B testing with model evaluation, canary deployments, automated rollback\n7. **Cost optimization**: Prompt compression, speculative decoding, model quantization (FP16→FP8→INT4)\n\nMost prod setups use a router model to classify intent and dispatch to specialized models.', timestamp: '2026-05-21T11:05:03Z', model: 'claude-4', tokens: 510, latency: 1400 },
  { id: 'm19', role: 'user', content: 'What is chain-of-thought prompting?', timestamp: '2026-05-21T11:10:00Z', model: 'gpt-4' },
  { id: 'm20', role: 'assistant', content: 'Chain-of-thought (CoT) prompting instructs models to show intermediate reasoning before the final answer. Instead of:\n\n**Q**: "24 cookies, 3 per bag, 4 friends get how many each?"\n**A**: "2"\n\nCoT prompts:\n**Q**: "24 cookies, 3 per bag, 4 friends"\n**A**: "24 cookies ÷ 3 per bag = 8 bags. 8 bags ÷ 4 friends = 2 bags each. Answer: 2"\n\nVariants include:\n- **Zero-shot CoT**: Just add "Let\'s think step by step"\n- **Few-shot CoT**: Provide reasoning examples\n- **Self-consistency**: Sample multiple CoT paths, take majority vote\n- **Tree-of-Thoughts**: Branch and explore reasoning paths explicitly', timestamp: '2026-05-21T11:10:03Z', model: 'gpt-4', tokens: 360, latency: 950, sources: [{ title: 'Chain-of-Thought Prompting', url: 'https://arxiv.org/abs/2201.11903', relevance: 0.97 }] },
  { id: 'm21', role: 'user', content: 'Compare vector databases', timestamp: '2026-05-21T11:15:00Z', model: 'claude-4' },
  { id: 'm22', role: 'assistant', content: '**Vector DB Comparison:**\n\n| Feature | Pinecone | Weaviate | Qdrant | pgvector | Milvus |\n|---------|----------|----------|--------|----------|-------|\n| Managed | Yes | Hybrid | Hybrid | Self | Self |\n| Index | HNSW | HNSW | HNSW | IVF/HNSW | IVF/HNSW |\n| Hybrid | No | Yes | Yes | Yes | No |\n| Filtering | Post-filter | Pre-filter | Pre-filter | Pre-filter | Pre-filter |\n| Scalability | Excellent | Good | Excellent | Moderate | Excellent |\n| Latency (P99) | 10ms | 20ms | 5ms | 30ms | 15ms |\n\n**Recommendations:**\n- Quickest start: Pinecone\n- Best self-hosted with filters: Qdrant\n- If already on Postgres: pgvector\n- Massive scale (100M+): Milvus\n- Multi-modal + hybrid: Weaviate', timestamp: '2026-05-21T11:15:03Z', model: 'claude-4', tokens: 430, latency: 1100, sources: [{ title: 'Vector DB Benchmark', url: 'https://qdrant.tech/benchmarks/', relevance: 0.91 }] },
];

export const mockWorkflows: Workflow[] = [
  { id: 'w1', name: 'Content Summarization Pipeline', description: 'Automatically summarizes incoming articles and documents using GPT-4', status: 'active', steps: 5, lastRun: '2 min ago', successRate: 97, avgLatency: 3400, category: 'NLP', tags: ['summarization', 'gpt-4', 'automation'], createdBy: 'alice@nova-ai.io', createdAt: '2026-03-15' },
  { id: 'w2', name: 'Data Enrichment ETL', description: 'Extracts, transforms, and enriches raw data with AI-generated metadata', status: 'active', steps: 8, lastRun: '5 min ago', successRate: 94, avgLatency: 8200, category: 'Data Processing', tags: ['etl', 'enrichment', 'pipeline'], createdBy: 'bob@nova-ai.io', createdAt: '2026-04-01' },
  { id: 'w3', name: 'Customer Support Triage', description: 'Routes and pre-answers support tickets using semantic intent classification', status: 'active', steps: 4, lastRun: '1 min ago', successRate: 99, avgLatency: 1200, category: 'Customer Success', tags: ['support', 'classification', 'routing'], createdBy: 'carol@nova-ai.io', createdAt: '2026-02-20' },
  { id: 'w4', name: 'Code Review Assistant', description: 'Analyzes PR diffs and generates code review comments with suggestions', status: 'active', steps: 6, lastRun: '10 min ago', successRate: 88, avgLatency: 5600, category: 'Engineering', tags: ['code-review', 'github', 'automation'], createdBy: 'dave@nova-ai.io', createdAt: '2026-04-10' },
  { id: 'w5', name: 'Market Research Aggregator', description: 'Scrapes and synthesizes market trends from multiple sources weekly', status: 'draft', steps: 7, lastRun: '2 days ago', successRate: 0, avgLatency: 0, category: 'Research', tags: ['scraping', 'analysis', 'reports'], createdBy: 'eve@nova-ai.io', createdAt: '2026-05-01' },
  { id: 'w6', name: 'Real-time Sentiment Monitor', description: 'Tracks brand sentiment across social media and news platforms', status: 'paused', steps: 3, lastRun: '1 week ago', successRate: 92, avgLatency: 2800, category: 'Analytics', tags: ['sentiment', 'social-media', 'monitoring'], createdBy: 'alice@nova-ai.io', createdAt: '2026-01-15' },
  { id: 'w7', name: 'Personalized Newsletter Generator', description: 'Curates and generates personalized newsletters based on user preferences', status: 'error', steps: 5, lastRun: '3 hours ago', successRate: 76, avgLatency: 4500, category: 'Content', tags: ['newsletter', 'personalization', 'content'], createdBy: 'bob@nova-ai.io', createdAt: '2026-03-20' },
  { id: 'w8', name: 'API Documentation Generator', description: 'Auto-generates API docs from OpenAPI specs using LLM description enhancement', status: 'active', steps: 4, lastRun: '15 min ago', successRate: 95, avgLatency: 2100, category: 'Engineering', tags: ['docs', 'openapi', 'automation'], createdBy: 'carol@nova-ai.io', createdAt: '2026-04-25' },
];

export const mockAgents: Agent[] = [
  { id: 'a1', name: 'Code Assistant', description: 'Multi-language programming assistant with real-time code generation and debugging', model: 'claude-4', status: 'online', capabilities: ['code-gen', 'debugging', 'refactoring', 'code-review'], temperature: 0.2, lastActive: 'Just now', totalRequests: 45230, avgResponseTime: 1800, systemPrompt: 'You are a world-class programming assistant.', memory: [{ type: 'Conversation', items: 150 }, { type: 'Code Snippets', items: 3200 }] },
  { id: 'a2', name: 'Data Analyzer', description: 'Statistical analysis and data visualization expert', model: 'gpt-4', status: 'online', capabilities: ['analysis', 'visualization', 'statistics', 'reporting'], temperature: 0.3, lastActive: '2 min ago', totalRequests: 28940, avgResponseTime: 2400, systemPrompt: 'You are a data science expert.', memory: [{ type: 'Datasets', items: 85 }, { type: 'Analysis History', items: 1200 }] },
  { id: 'a3', name: 'Content Writer', description: 'Creative and technical writing across formats and tones', model: 'claude-4', status: 'online', capabilities: ['writing', 'editing', 'summarization', 'translation'], temperature: 0.7, lastActive: '5 min ago', totalRequests: 38120, avgResponseTime: 2200, systemPrompt: 'You are a versatile writer and editor.', memory: [{ type: 'Style Profiles', items: 25 }, { type: 'Drafts', items: 890 }] },
  { id: 'a4', name: 'Research Assistant', description: 'Deep research with web search and source synthesis', model: 'gpt-4', status: 'training', capabilities: ['web-search', 'analysis', 'citation', 'summarization'], temperature: 0.4, lastActive: '1 hour ago', totalRequests: 15780, avgResponseTime: 3200, systemPrompt: 'You are a thorough research assistant.', memory: [{ type: 'Research Topics', items: 45 }, { type: 'Sources', items: 2100 }] },
  { id: 'a5', name: 'Image Analyst', description: 'Computer vision and image analysis specialist', model: 'gpt-4', status: 'offline', capabilities: ['classification', 'detection', 'ocr', 'captioning'], temperature: 0.1, lastActive: '1 day ago', totalRequests: 8950, avgResponseTime: 4100, systemPrompt: 'You are an expert computer vision system.', memory: [{ type: 'Image Cache', items: 1200 }, { type: 'Training Data', items: 5000 }] },
  { id: 'a6', name: 'Orchestrator', description: 'Meta-agent that routes tasks to specialized sub-agents', model: 'gpt-4', status: 'online', capabilities: ['routing', 'planning', 'decomposition', 'monitoring'], temperature: 0.3, lastActive: 'Just now', totalRequests: 62100, avgResponseTime: 600, systemPrompt: 'You are an intelligent task router and orchestrator.', memory: [{ type: 'Agent Registry', items: 12 }, { type: 'Task History', items: 4500 }] },
];

export const mockKnowledge: KnowledgeItem[] = [
  { id: 'k1', title: 'GPT-4 Technical Report', content: 'Full technical report detailing GPT-4 architecture, capabilities, and safety evaluations', type: 'document', source: 'arxiv.org', status: 'indexed', chunks: 48, embeddings: 'text-embedding-3-large', lastUpdated: '2026-05-20', tags: ['llm', 'gpt-4', 'architecture'], size: '2.4 MB' },
  { id: 'k2', title: 'Vector Search Implementation Guide', content: 'Step-by-step guide to implementing vector search with HNSW indexes and hybrid ranking', type: 'article', source: 'pinecone.io', status: 'indexed', chunks: 24, embeddings: 'text-embedding-3-small', lastUpdated: '2026-05-19', tags: ['vector-search', 'hnsw', 'tutorial'], size: '890 KB' },
  { id: 'k3', title: 'React Hooks API Reference', content: 'Complete API documentation for all React hooks including useEffect, useMemo, useCallback', type: 'document', source: 'react.dev', status: 'indexed', chunks: 36, embeddings: 'text-embedding-3-large', lastUpdated: '2026-05-18', tags: ['react', 'hooks', 'frontend'], size: '1.8 MB' },
  { id: 'k4', title: 'Transformer from Scratch', content: 'PyTorch implementation of a transformer model with multi-head attention and positional encoding', type: 'code', source: 'github.com', status: 'indexed', chunks: 12, embeddings: 'text-embedding-3-small', lastUpdated: '2026-05-17', tags: ['transformer', 'pytorch', 'deep-learning'], size: '340 KB' },
  { id: 'k5', title: 'Customer Support Transcripts Q2 2026', content: 'Anonymized customer support interactions for training classification models', type: 'dataset', source: 'internal', status: 'indexed', chunks: 156, embeddings: 'text-embedding-3-large', lastUpdated: '2026-05-16', tags: ['support', 'dataset', 'classification'], size: '45 MB' },
  { id: 'k6', title: 'RAG System Design Patterns', content: 'Architecture patterns for building production RAG systems with routing and caching', type: 'article', source: 'medium.com', status: 'processing', chunks: 18, embeddings: 'text-embedding-3-small', lastUpdated: '2026-05-15', tags: ['rag', 'architecture', 'patterns'], size: '1.2 MB' },
  { id: 'k7', title: 'Python AsyncIO Best Practices', content: 'Guide to writing efficient async Python code with asyncio and aiohttp', type: 'document', source: 'docs.python.org', status: 'indexed', chunks: 20, embeddings: 'text-embedding-3-small', lastUpdated: '2026-05-14', tags: ['python', 'asyncio', 'backend'], size: '560 KB' },
  { id: 'k8', title: 'Fine-tuning LLMs with LoRA', content: 'Practical guide to parameter-efficient fine-tuning using Low-Rank Adaptation', type: 'article', source: 'huggingface.co', status: 'failed', chunks: 0, embeddings: 'text-embedding-3-large', lastUpdated: '2026-05-13', tags: ['fine-tuning', 'lora', 'llm'], size: '780 KB' },
  { id: 'k9', title: 'E-Commerce Product Catalog', content: 'Product catalog with descriptions, categories, and attributes for recommendation system', type: 'dataset', source: 'internal', status: 'indexed', chunks: 210, embeddings: 'text-embedding-3-large', lastUpdated: '2026-05-12', tags: ['ecommerce', 'dataset', 'recommendations'], size: '120 MB' },
  { id: 'k10', title: 'LangChain Agent Tutorial', content: 'Complete tutorial for building custom agents with LangChain including tool definitions', type: 'code', source: 'github.com', status: 'indexed', chunks: 15, embeddings: 'text-embedding-3-small', lastUpdated: '2026-05-11', tags: ['langchain', 'agents', 'tutorial'], size: '420 KB' },
  { id: 'k11', title: 'Neural Network Quantization Guide', content: 'Guide to quantization techniques: PTQ, QAT, INT8, FP8 for model optimization', type: 'document', source: 'nvidia.com', status: 'indexed', chunks: 30, embeddings: 'text-embedding-3-large', lastUpdated: '2026-05-10', tags: ['quantization', 'optimization', 'deployment'], size: '1.1 MB' },
  { id: 'k12', title: 'Multi-Modal Embedding Models', content: 'Comparison of CLIP, ImageBind, and other multi-modal embedding approaches', type: 'article', source: 'arxiv.org', status: 'processing', chunks: 8, embeddings: 'text-embedding-3-small', lastUpdated: '2026-05-09', tags: ['embeddings', 'multimodal', 'research'], size: '950 KB' },
];

export const mockPrompts: Prompt[] = [
  { id: 'p1', name: 'Code Review Prompt', content: 'Review the following code diff and provide feedback on:\n1. Code quality and best practices\n2. Potential bugs or edge cases\n3. Performance considerations\n4. Security concerns\n5. Suggestions for improvement\n\nFocus on actionable, concise feedback.', model: 'claude-4', temperature: 0.2, maxTokens: 2048, variables: ['diff_content', 'language'], tags: ['code-review', 'engineering'], version: 3, author: 'dave@nova-ai.io', createdAt: '2026-03-01', updatedAt: '2026-05-15' },
  { id: 'p2', name: 'Summarization Template', content: 'Summarize the following text in {{language}} at a {{reading_level}} reading level.\n\nFocus on key points and actionable insights.\n\nTarget length: {{target_length}} sentences.\n\nText:\n{{input_text}}', model: 'gpt-4', temperature: 0.3, maxTokens: 1024, variables: ['input_text', 'language', 'reading_level', 'target_length'], tags: ['summarization', 'nlp'], version: 5, author: 'alice@nova-ai.io', createdAt: '2026-02-10', updatedAt: '2026-05-18' },
  { id: 'p3', name: 'Sentiment Classifier', content: 'Classify the sentiment of the following text as Positive, Negative, or Neutral.\n\nProvide:\n1. Sentiment label\n2. Confidence score (0-1)\n3. Key emotional indicators\n4. Suggested action (if any)\n\nText: {{input_text}}', model: 'gpt-4', temperature: 0.1, maxTokens: 512, variables: ['input_text'], tags: ['classification', 'sentiment'], version: 2, author: 'alice@nova-ai.io', createdAt: '2026-01-20', updatedAt: '2026-04-10' },
  { id: 'p4', name: 'SQL Generator', content: 'Generate a {{dialect}} SQL query for the following request:\n\n{{user_request}}\n\nDatabase schema:\n{{schema}}\n\nReturn only the SQL query, wrapped in a code block.', model: 'claude-4', temperature: 0.1, maxTokens: 1024, variables: ['dialect', 'user_request', 'schema'], tags: ['sql', 'database', 'engineering'], version: 4, author: 'dave@nova-ai.io', createdAt: '2026-03-15', updatedAt: '2026-05-20' },
  { id: 'p5', name: 'Creative Writing Prompt', content: 'Write a {{genre}} piece about {{topic}}.\n\nTone: {{tone}}\n\nAudience: {{audience}}\n\nLength: {{length}} words\n\nInclude:\n- A strong opening hook\n- Vivid sensory details\n- Natural dialogue (if applicable)\n- A satisfying conclusion', model: 'claude-4', temperature: 0.8, maxTokens: 4096, variables: ['genre', 'topic', 'tone', 'audience', 'length'], tags: ['writing', 'creative', 'content'], version: 2, author: 'carol@nova-ai.io', createdAt: '2026-04-01', updatedAt: '2026-05-12' },
  { id: 'p6', name: 'Data Analysis Report', content: 'Analyze the following dataset and provide:\n1. Summary statistics\n2. Key trends and patterns\n3. Anomalies detected\n4. Recommendations\n5. Visualizations to create\n\nData:\n{{dataset}}\n\nContext: {{context}}', model: 'gpt-4', temperature: 0.3, maxTokens: 3072, variables: ['dataset', 'context'], tags: ['analysis', 'data', 'reporting'], version: 3, author: 'bob@nova-ai.io', createdAt: '2026-02-20', updatedAt: '2026-05-16' },
  { id: 'p7', name: 'Translation with Context', content: 'Translate the following text from {{source_language}} to {{target_language}}.\n\nContext: {{context}}\n\nStyle: {{style}}\n\nText:\n{{input_text}}\n\nProvide the translation followed by a brief note on key translation choices.', model: 'gpt-4', temperature: 0.3, maxTokens: 2048, variables: ['source_language', 'target_language', 'context', 'style', 'input_text'], tags: ['translation', 'nlp'], version: 2, author: 'carol@nova-ai.io', createdAt: '2026-03-25', updatedAt: '2026-05-08' },
  { id: 'p8', name: 'System Prompt Builder', content: 'You are {{role}} with expertise in {{expertise}}.\n\nYour responsibilities:\n{{responsibilities}}\n\nGuidelines:\n- {{guideline_1}}\n- {{guideline_2}}\n- {{guideline_3}}\n\nOutput format: {{output_format}}\n\nAlways stay in character and follow these instructions precisely.', model: 'claude-4', temperature: 0.5, maxTokens: 2048, variables: ['role', 'expertise', 'responsibilities', 'guideline_1', 'guideline_2', 'guideline_3', 'output_format'], tags: ['system-prompt', 'agents'], version: 6, author: 'admin@nova-ai.io', createdAt: '2026-01-05', updatedAt: '2026-05-20' },
];

export const kpiData = {
  activeWorkflows: 5,
  onlineAgents: 4,
  knowledgeItems: 12,
  totalPrompts: 8,
  avgResponseTime: 1.8,
  tokensToday: 1452300,
  tokensTrend: '+12%',
  responseTimeTrend: '-8%',
};
